# all points are in skimage's coordinate system; i.e. (x, y) where x is 0 at top, y is 0 at left.

# float = [float, float]
pivot_position = [79, 74]

# int temperature = [float x, float y]
# where (x, y) is the position of any pixel on the black line representing that temperature
[temperature_positions]
 -30 = [113.4,  24.5]
 -10 = [ 90.7,  11.2]
  10 = [ 56.6,  10.7]
  30 = [ 25.4,  31.2]
  50 = [  7.7,  66.3]
  70 = [ 16.6, 103.5]
  90 = [ 40.4, 131.1]
 110 = [ 76.2, 137.6]
 130 = [109.1, 125.4]

